### ISSUE TITLE
foreach support in traversals

### ISSUE THREAD

**Issue by ManfredLange** [JanusGraph/janusgraph-dotnet#70]
I may be overlooking something but I'd like to suggest this anyway.

To iterate over a set of vertices (or edges), I can write the following:
```csharp
var t = g.V().HasLabel("FooBar");
while(t.MoveNext())
{
   var vertex = t.Current;
   Console.WriteLine($"{vertex.Id}");
}
```

However, in C# I'd typically prefer to write something like:

```csharp
var t = g.V().HasLabel("FooBar");
foreach(var vertex in t)
{
   Console.WriteLine($"{vertex.Id}");
}
```

For that to work the underlying class - `GraphTraversal<V1, >` - would need to implement a method named `GetEnumerator()` which at present it does not.

It'd be great if this support could be added. Thank you!

**Comment by FlorianHockmann** [comment]
What you're asking for is not really specific to JanusGraph but about [Gremlin.Net](http://tinkerpop.apache.org/docs/current/reference/#gremlin-DotNet) in general, the underlying Gremlin implementation in .NET. So, a better place to ask for this would the [Gremlin users Google group](https://groups.google.com/g/gremlin-users).

But let me try to give you an answer nevertheless:

.NET has two interfaces to support iteration: [`IEnumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=netframework-4.7.2) and [`IEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator?view=netframework-4.7.2).

An `IEnumerator` supports iteration over a collection and an `IEnumerable` returns an `IEnumerator` with the method `GetEnumerator()`. A Gremlin traversal allows to iterate over the graph and it provides methods like `Next()` and `HasNext()` in all languages, so not only in .NET, but also in Java, Python, and Javascript. These methods are a good match for .NET's `IEnumerator` interface which contains the method `MoveNext()`. So, it seemed very natural that `ITraversal` (which is implemented by `GraphTraversal`) should implement `IEnumerator` in .NET.

An `IEnumerable` on the other hand is something that returns an `IEnumerator` which can then be iterated over. It is also important that the returned `IEnumerator` is always a new object as you would get into problems otherwise if you have nested `foreach` loops over the same `IEnumerable`.

Since it's the traversal itself that is being iterated, `IEnumerator` seems to me like the right choice to implement in .NET for Gremlin traversals.


But you can still easily use a traversal in a `foreach` loop. You can just call `ToList()` on it:

```c#
foreach (var vertex in g.V().HasLabel("FooBar").ToList())
{
    Console.WriteLine($"{vertex.Id}");
}
```

**Comment by ManfredLange** [comment]
@FlorianHockmann Thanks for the explanation.
